### PR TITLE
Update jobs links

### PR DESCRIPTION
**Pull request by David-Wobrock**
I hesitated with a link to `.../careers/engineering/` since we are on the developers website

### CODE REVIEW

**Comment by jbbarth** [comment]
Oops, someone else broke Travis?

The absolute links look good to me 👍

**Comment by David-Wobrock** [comment]
@jbbarth Yep, Travis is not happy :( I'll see if I can fix the tests

Sorry, I should have been explicit. I meant that I hesitated putting an absolute link to the engineering jobs:
`https://www.botify.com/careers/engineering/`

**Comment by David-Wobrock** [comment]
@jbbarth Travis :heavy_check_mark:

**Comment by jbbarth** [comment]
@David-Wobrock good :) I put "PR: Review OK", I let you merge _and_ deploy to production? Thanks!!

**Pull request merged**
